name="Vikas Kumar"
print(name[1])
print(name[-1])
print(name[0:5])
print(name[-1:])
print(name[1:])
print(name[:5])
print(name[::2])
print(name[::-1])
print(name[-1:-6:-1])
print("Arpit Varman"[::-1])